// BOLD
export { default as PHCheckCircleBoldIcon } from './CheckCircleBoldIcon.svelte'
export { default as PHDotsThreeBoldIcon } from './DotsThreeBoldIcon.svelte'
export { default as PHPlusBoldIcon } from './PlusBoldIcon.svelte'
export { default as PHTrashBoldIcon } from './TrashBoldIcon.svelte'
export { default as PHFolderOpenBoldIcon } from './FolderOpenBoldIcon.svelte'
export { default as PHMagnifyingGlassBoldIcon } from './MagnifyingGlassBoldIcon.svelte'
export { default as PHXBoldIcon } from './XBoldIcon.svelte'
export { default as PHHouseBoldIcon } from './HouseBoldIcon.svelte'
export { default as PHGitForkBoldIcon } from './GitForkBoldIcon.svelte'
export { default as PHGearBoldIcon } from './GearBoldIcon.svelte'
export { default as PHInfoBoldIcon } from './InfoBoldIcon.svelte'
export { default as PHWarningBoldIcon } from './WarningBoldIcon.svelte'
export { default as PHProhibitedBoldIcon } from './ProhibitedBoldIcon.svelte'
export { default as PHCaretLeftBoldIcon } from './CaretLeftBoldIcon.svelte'
export { default as PHCaretRightBoldIcon } from './CaretRightBoldIcon.svelte'
export { default as PHArrowClockwiseBoldIcon } from './ArrowClockwiseBoldIcon.svelte'
export { default as PHMinusBoldIcon } from './MinusBoldIcon.svelte'
export { default as PHArrowsInSimpleBoldIcon } from './ArrowsInSimpleBoldIcon.svelte'
export { default as PHArrowsOutSimpleBoldIcon } from './ArrowsOutSimpleBoldIcon.svelte'
export { default as PHTrayArrowDownBoldIcon } from './TrayArrowDownBoldIcon.svelte'
export { default as PHQuestionMarkBoldIcon } from './QuestionMarkBoldIcon.svelte'
export { default as PHCheckBoldIcon } from './CheckBoldIcon.svelte'
export { default as PHCaretUpDownBoldIcon } from './CaretUpDownBoldIcon.svelte'
export { default as PHCaretUpBoldIcon } from './CaretUpBoldIcon.svelte'
export { default as PHCaretDownBoldIcon } from './CaretDownBoldIcon.svelte'
export { default as PHListBoldIcon } from './ListBoldIcon.svelte'
export { default as PHSortAscendingBoldIcon } from './SortAscendingIcon.svelte'
export { default as PHSortDescendingIcon } from './SortDescendingIcon.svelte'
export { default as PHWifiHighBoldIcon } from './WifiHighBoldIcon.svelte'
export { default as PHEyeBoldIcon } from './EyeBoldIcon.svelte'
export { default as PHEyeClosedBoldIcon } from './EyeClosedBoldIcon.svelte'
export { default as PHPencilBoldIcon } from './PencilBoldIcon.svelte'

// DUOTONE
export { default as PHHandHeartDuotoneIcon } from './HandHeartDuotoneIcon.svelte'
